services:
  - type: web
    name: PrepWise
    env: python
    buildCommand: pip uninstall -y bcrypt passlib  
    buildCommand: pip install bcrypt==4.2.0 passlib==1.7.4
    buildCommand: pip install -r requirements.txt


    startCommand: uvicorn app.main:app --host 127.0.0.1 --port 8000
