services:
  - type: web
    name: PrepWise
    env: python
    buildCommand: pip install -r requirements.txt , pip uninstall -y bcrypt passlib , pip install bcrypt==4.2.0 passlib==1.7.4


    startCommand: uvicorn app.main:app --host 0.0.0.0 --port 10000
